### ISSUE TITLE
i am training this rasa with new templates,but it is not affecting in UI

### ISSUE THREAD

**Issue by Aniket573** [kbrajwani/blog#3]

**Comment by kbrajwani** [comment]
ok its becuase in script.js file i putted public url 
url: 'https://rasablog.herokuapp.com/webhooks/rest/webhook',
you can chnage this with local and problem will be solve.

**Comment by Aniket573** [comment]
i used http://localhost:5005/webhooks/rest/webhook but still no luck.

**Comment by kbrajwani** [comment]
check in browser console that you are using latest script.js or do ctrl + f5 to reload with new js

**Comment by Aniket573** [comment]
I updated url in rasadjango/static/js and in rasaweb/static/js but i am getting output as "I couldn't get that. Let' try something else!" after typing hi,but i am not getting output as "Hey!how are you!hope you are good",though i am getting "Hey!how are you!hope you are good" in rasa shell.Please suggest.

**Comment by Aniket573** [comment]
Also can you check if this is working with updated training data from your end?

**Comment by Aniket573** [comment]
Thanks it worked.
